# config/default_config.yaml

# CVSS subscore thresholds (0–1 scale)
cvss_confidentiality_threshold: 0.5
cvss_integrity_threshold: 0.5
cvss_availability_threshold: 0.7

# Exploit flag: Whether any exploit exists
exploit_flag: true

# CISA KEV flag: If a CVE is in CISA KEV list
cisa_kev_flag: true

# Runtime-critical component patterns
runtime_critical_keywords:
  - kernel
  - libc
  - systemd

# Model hyperparameters
models:
  random_forest:
    n_estimators: 200
    max_depth: 10
    min_samples_split: 5
    random_state: 42
  lightgbm:
    learning_rate: 0.05
    num_leaves: 31
    max_depth: 10
    boosting_type: gbdt
    random_state: 42
  catboost:
    iterations: 300
    depth: 6
    learning_rate: 0.1
    loss_function: Logloss
    verbose: 0
